package main;

import com.mysql.cj.jdbc.MysqlDataSource;
import com.toedter.calendar.JDateChooser;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class AddCustomer extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton jButtonBrowse;
	private JButton jButtonAdd;
	private JButton jButtonCancel;
	private JLabel jLabelFirstName;
	private JLabel jLabelContact;
	private JLabel jLabelLastName;
	private JLabel jLabelNicNo;
	private JLabel jLabelPassportID;
	private JLabel jLabelAddress;
	private JLabel jLabelCustID;
	private JLabel jLabelDOB;
	private JLabel jLabelGender;
	private JPanel jPanel1;
	private JPanel jPanel2;
	private JScrollPane jScrollPaneAddress;
	private JLabel txtphoto;
	private JTextField txtfirstname;
	private JTextField txtlastname;
	private JTextField txtnic;
	private JLabel txtid;
	private JTextField txtpassport;
	private JTextArea txtaddress;
	private JDateChooser txtdob;
	private JRadioButton radioButtonMale;
	private JRadioButton radioButtonFemale;
	private JTextField txtcontact;
	// End of variables declaration//GEN-END:variables

	String statementString;
	ResultSet rs;
	Statement statement;
	JFileChooser fileChooser;
	MysqlDataSource d = null;
	Connection con;
	PreparedStatement pst;
	String path = null;
	byte[] userimage = null;


	public JRadioButton getRadioButtonMale() {
		return radioButtonMale;
	}

	public JRadioButton getRadioButtonFemale() {
		return radioButtonFemale;
	}

	public void setRadioButtonMale(boolean selected) {
		this.radioButtonMale.setSelected(selected);
	}

	public void setRadioButtonFemale(boolean selected) {
		this.radioButtonFemale.setSelected(selected);
	}

	public void setTxtfirstname(String firstName) {
		this.txtfirstname.setText(firstName);
	}

	public void setTxtlastname(String lastname) {
		this.txtlastname.setText(lastname);
	}

	public void setTxtnic(String newNic) {
		this.txtnic.setText(newNic);
	}

	public void setTxtpassport(String passportNum) {
		this.txtpassport.setText(passportNum);
	}

	public void setTxtaddress(String address) {
		this.txtaddress.setText(address);
	}

	public void setTxtcontact(String contact) {
		this.txtcontact.setText(contact);
	}

	public void setTxtdob(Date dob) {
		this.txtdob.setDate(dob);
	}

	public JButton getjButtonBrowse() {
		return jButtonBrowse;
	}

	public JButton getjButtonAdd() {
		return jButtonAdd;
	}

	public JButton getjButtonCancel() {
		return jButtonCancel;
	}

	public void setPst(String query) throws SQLException {
		d = new MysqlDataSource();
		d.setUser("root");
		d.setPassword("1234");
		d.setDatabaseName("airline");
		con =  d.getConnection();
		pst = con.prepareStatement(query);
	}

	public void setStatementString(String query) {
	statementString = query;
	}

	public AddCustomer(MysqlDataSource ds, JFileChooser chooser) {
		initComponents();
		this.d = ds;
		this.fileChooser = chooser;
	}

	/**
	 * Creates new form AddCustomer
	 */
	public AddCustomer() {
		initComponents();
		autoID();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new JPanel();
		jLabelFirstName = new JLabel();
		jLabelLastName = new JLabel();
		jLabelNicNo = new JLabel();
		jLabelPassportID = new JLabel();
		jLabelAddress = new JLabel();
		txtlastname = new JTextField();
		txtfirstname = new JTextField();
		txtnic = new JTextField();
		txtpassport = new JTextField();
		jScrollPaneAddress = new JScrollPane();
		txtaddress = new JTextArea();
		jLabelCustID = new JLabel();
		txtid = new JLabel();
		jPanel2 = new JPanel();
		jLabelDOB = new JLabel();
		jLabelGender = new JLabel();
		jLabelContact = new JLabel();
		txtdob = new JDateChooser();
		radioButtonMale = new JRadioButton();
		radioButtonFemale = new JRadioButton();
		txtcontact = new JTextField();
		txtphoto = new JLabel();
		jButtonBrowse = new JButton();
		jButtonAdd = new JButton();
		jButtonCancel = new JButton();

txtfirstname.setName("firstname");
txtlastname.setName("lastname");
txtnic.setName("nic");
txtpassport.setName("passport");
txtaddress.setName("address");
txtdob.setName("date");
radioButtonMale.setName("male");
txtcontact.setName("contact");
jButtonAdd.setName("add");
jButtonCancel.setName("cancel");
jButtonBrowse.setName("browse");


		jPanel1.setBackground(new java.awt.Color(51, 0, 255));

		jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelFirstName.setForeground(new java.awt.Color(255, 255, 255));
		jLabelFirstName.setText("First Name");

		jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelLastName.setForeground(new java.awt.Color(255, 255, 255));
		jLabelLastName.setText("Last Name");

		jLabelNicNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelNicNo.setForeground(new java.awt.Color(255, 255, 255));
		jLabelNicNo.setText("Nic No");

		jLabelPassportID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelPassportID.setForeground(new java.awt.Color(255, 255, 255));
		jLabelPassportID.setText("Passport ID");

		jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelAddress.setForeground(new java.awt.Color(255, 255, 255));
		jLabelAddress.setText("Address");

		txtaddress.setColumns(20);
		txtaddress.setRows(5);
		jScrollPaneAddress.setViewportView(txtaddress);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(26, 26, 26)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														false)
												.addGroup(jPanel1Layout
														.createSequentialGroup()
														.addComponent(
																jLabelFirstName)
														.addGap(47, 47, 47)
														.addComponent(
																txtfirstname))
												.addGroup(jPanel1Layout
														.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jLabelAddress)
																.addComponent(
																		jLabelPassportID)
																.addComponent(
																		jLabelNicNo))
														.addGap(38, 38, 38)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(
																		jScrollPaneAddress)
																.addComponent(
																		txtpassport)
																.addComponent(
																		txtnic))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jLabelLastName)
										.addGap(48, 48, 48)
										.addComponent(txtlastname,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												166,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(37, 37, 37)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelFirstName)
								.addComponent(txtfirstname,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(22, 22, 22)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelLastName)
								.addComponent(txtlastname,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelNicNo).addComponent(txtnic,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelPassportID)
								.addComponent(txtpassport,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelAddress)
								.addComponent(jScrollPaneAddress,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										62,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(34, 34, 34)));

		jLabelCustID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabelCustID.setText("Customer ID");

		txtid.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
		txtid.setForeground(new java.awt.Color(255, 0, 0));
		txtid.setText("0" + txtid.getText());

		jPanel2.setBackground(new java.awt.Color(51, 0, 255));

		jLabelDOB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelDOB.setForeground(new java.awt.Color(255, 255, 255));
		jLabelDOB.setText("Date of Birth");

		jLabelGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelGender.setForeground(new java.awt.Color(255, 255, 255));
		jLabelGender.setText("Gender");

		jLabelContact.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelContact.setForeground(new java.awt.Color(255, 255, 255));
		jLabelContact.setText("Contact");

		radioButtonMale.setText("Male");
		radioButtonFemale.setText("Female");

		radioButtonMale.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				radioButtonFemale.setSelected(false);
			}
		});
		radioButtonFemale.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				radioButtonMale.setSelected(false);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(22, 22, 22)
						.addGroup(jPanel2Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelDOB)
								.addComponent(txtdob,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										174, Short.MAX_VALUE)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelGender)
												.addComponent(jLabelContact))
										.addGap(43, 43, 43)
										.addGroup(jPanel2Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														false)
												.addGroup(jPanel2Layout
														.createSequentialGroup()
														.addComponent(
																radioButtonMale)
														.addGap(18, 18, 18)
														.addComponent(
																radioButtonFemale))
												.addComponent(txtcontact))))
						.addContainerGap(41, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(37, 37, 37).addComponent(jLabelDOB)
						.addComponent(txtdob,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelGender)
								.addComponent(radioButtonMale)
								.addComponent(radioButtonFemale))

						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelContact)
								.addComponent(txtcontact,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(108, Short.MAX_VALUE)));

		txtphoto.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jButtonBrowse.setText("Browse");
		jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonBrowseActionPerformed(evt);
			}
		});

		jButtonAdd.setText("Add");
		jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAddActionPerformed(evt);
			}
		});

		jButtonCancel.setText("Cancel");
		jButtonCancel.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(25, 25, 25).addComponent(jLabelCustID)
								.addGap(50, 50, 50).addComponent(txtid))
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout
																.createSequentialGroup()
																.addComponent(
																		jPanel2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		txtphoto,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		250,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout
																.createSequentialGroup()
																.addGap(337,
																		337,
																		337)
																.addComponent(
																		jButtonBrowse,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		87,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGroup(layout.createSequentialGroup()
												.addGap(39, 39, 39)
												.addComponent(jButtonAdd,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														105,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jButtonCancel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														100,
														javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addContainerGap(24, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelCustID).addComponent(txtid))
						.addGap(41, 41, 41)
						.addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING,
								false)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup()
										.addGap(25, 25, 25)
										.addGroup(layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(txtphoto,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														250, Short.MAX_VALUE)
												.addComponent(jPanel2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addComponent(jButtonBrowse,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButtonAdd,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														38,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButtonCancel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														38,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(49, 49, 49)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void autoID() {
		try {

			if(d == null) {
				d = new MysqlDataSource();
				d.setUser("root");
				d.setPassword("1234");
				d.setDatabaseName("airline");
			}
			con =  d.getConnection();


			if(statementString == null) {
				statement = con.createStatement();
				rs = statement.executeQuery("select MAX(id) from customer");
			} else {
				rs = statement.executeQuery(statementString);
			}
			rs.next();
			rs.getString("MAX(id)");
			if (rs.getString("MAX(id)") == null) {
				txtid.setText("CS001");
			} else {
				long id = Long.parseLong(rs.getString("MAX(id)").substring(2,
						rs.getString("MAX(id)").length()));
				id++;
				txtid.setText("CS" + String.format("%03d", id));

			}

		} catch (SQLException ex) {
			Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE,
					null, ex);
		}

	}

	public void setUserImageWithPath(String path) throws IOException {
		File image = new File(path);
		FileInputStream fis = new FileInputStream(image);
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		byte[] buff = new byte[1024];
		for (int readNum; (readNum = fis.read(buff)) != -1;) {
			baos.write(buff, 0, readNum);
		}
		userimage = baos.toByteArray();
		fis.close();
	}

	public boolean jButtonBrowseActionPerformed(ActionEvent evt) {

		try {

			if(path == null) {

				if(fileChooser == null) {
					fileChooser = new JFileChooser();
				}

				fileChooser.showOpenDialog(null);
				File pic = fileChooser.getSelectedFile();
				FileNameExtensionFilter filter = new FileNameExtensionFilter(
						"*.images", "png", "jpg");
				fileChooser.addChoosableFileFilter(filter);
				path = pic.getAbsolutePath();
				BufferedImage img;
				img = ImageIO.read(fileChooser.getSelectedFile());
				ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage()
						.getScaledInstance(250, 250, Image.SCALE_DEFAULT));
				txtphoto.setIcon(imageIcon);
			}
			File image = new File(path);
			FileInputStream fis = new FileInputStream(image);
			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			byte[] buff = new byte[1024];
			for (int readNum; (readNum = fis.read(buff)) != -1;) {
				baos.write(buff, 0, readNum);
			}
			userimage = baos.toByteArray();
			fis.close();

		} catch (IOException ex) {
			Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE,
					null, ex);
			return false;
		}
return true;
	}

	public boolean jButtonAddActionPerformed(ActionEvent evt) {

		if(!txtfirstname.getText().isBlank() && !txtlastname.getText().isBlank() && !txtnic.getText().isBlank() &&
				!txtpassport.getText().isBlank() && !txtaddress.getText().isBlank() && (radioButtonMale.isSelected() || radioButtonFemale.isSelected())) {


			Pattern nicPattern = Pattern.compile("^[0-9]{9}+[A-Z]$");
			Matcher nicMatcher = nicPattern.matcher(txtnic.getText());
			boolean nicFlag = nicMatcher.matches();

			Pattern passportPattern = Pattern.compile("^[0-9]{6}$");
			Matcher passportMatcher = passportPattern.matcher(txtpassport.getText());
			boolean passportFlag = passportMatcher.matches();

			if(!nicFlag) {
				JOptionPane.showMessageDialog(null, "Invalid Nic..");
				return false;
			}

			if(!passportFlag) {
				JOptionPane.showMessageDialog(null, "Invalid passport id..");
				return false;
			}

				String id = txtid.getText();
				String firstname = txtfirstname.getText();
				String lastname = txtlastname.getText();
				String nic = txtnic.getText();
				String passport = txtpassport.getText();
				String address = txtaddress.getText();
				try {
					DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
					String date = da.format(txtdob.getDate());

					String gender;
					if (radioButtonMale.isSelected())
						gender = "Male";
					else
						gender = "Female";

					String contact = txtcontact.getText();

					// Database code here:

					if (d == null) {
						d = new MysqlDataSource();
						d.setUser("root");
						d.setPassword("1234");
						d.setDatabaseName("airline");
					}
					con = d.getConnection();


					pst = con.prepareStatement(
							"insert into customer(id,firstname,lastname,nic,passport,address,dob,gender,contact,photo)values(?,?,?,?,?,?,?,?,?,?)");

					pst.setString(1, id);
					pst.setString(2, firstname);
					pst.setString(3, lastname);
					pst.setString(4, nic);
					pst.setString(5, passport);
					pst.setString(6, address);
					pst.setString(7, date);
					pst.setString(8, gender);
					pst.setString(9, contact);
					pst.setBytes(10, userimage);
					pst.executeUpdate();

					JOptionPane.showMessageDialog(null, "Registration Created...");

				} catch (SQLException ex) {
					Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE,
							null, ex);
					return false;
				}

		} else {
			JOptionPane.showMessageDialog(null, "Field Left Empty..");
			return false;
		}
		return true;
	}

	public void jButtonCancelActionPerformed(ActionEvent evt) {
		this.hide();
	}
}
