package main;

import com.toedter.calendar.JDateChooser;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Addflight extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton jButtonAdd;
	private JButton jButtonCancel;
	private JLabel jLabelFlightID;
	private JLabel jLabelFlightName;
	private JLabel jLabelSource;
	private JLabel jLabelDeparture;
	private JLabel jLabelDate;
	private JLabel jLabelDepTime;
	private JLabel jLabelArrTime;
	private JLabel jLabelFlightCharge;
	private JPanel jPanel1;
	private JTextField txtarrtime;
	private JDateChooser txtdate;
	private JComboBox<String> txtdepart;
	private JTextField txtdtime;
	private JTextField txtflightcharge;
	private JTextField txtflightid;
	private JTextField txtflightname;
	private JComboBox<String> txtsource;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form Addflight
	 */
	public Addflight() {
		initComponents();
		autoID();
	}

	Connection con;
	PreparedStatement pst;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new JPanel();
		jLabelFlightID = new JLabel();
		txtflightid = new JTextField();
		jLabelFlightName = new JLabel();
		jLabelSource = new JLabel();
		jLabelDeparture = new JLabel();
		txtflightname = new JTextField();
		jLabelDate = new JLabel();
		txtdate = new JDateChooser();
		jLabelDepTime = new JLabel();
		txtdtime = new JTextField();
		txtarrtime = new JTextField();
		jLabelArrTime = new JLabel();
		jLabelFlightCharge = new JLabel();
		txtflightcharge = new JTextField();
		jButtonAdd = new JButton();
		jButtonCancel = new JButton();
		txtsource = new JComboBox<>();
		txtdepart = new JComboBox<>();

		jPanel1.setBackground(new Color(51, 51, 255));

		jLabelFlightID.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabelFlightID.setForeground(new Color(255, 255, 255));
		jLabelFlightID.setText("Flight ID");

		txtflightid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		txtflightid.setForeground(new Color(255, 255, 0));
		txtflightid.setText(txtflightid.getText());

		jLabelFlightName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelFlightName.setForeground(new Color(255, 255, 255));
		jLabelFlightName.setText("Flight Name");

		jLabelSource.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelSource.setForeground(new Color(255, 255, 255));
		jLabelSource.setText("Source");

		jLabelDeparture.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelDeparture.setForeground(new Color(255, 255, 255));
		jLabelDeparture.setText("Departure");

		jLabelDate.setForeground(new Color(255, 255, 255));
		jLabelDate.setText("Date");

		jLabelDepTime.setForeground(new Color(255, 255, 255));
		jLabelDepTime.setText("Dep Time");

		jLabelArrTime.setForeground(new Color(255, 255, 255));
		jLabelArrTime.setText("Arr Time");

		jLabelFlightCharge.setForeground(new Color(255, 255, 255));
		jLabelFlightCharge.setText("Flight Charge");

		jButtonAdd.setText("Add");
		jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAddActionPerformed(evt);
			}
		});

		jButtonCancel.setText("Cancel");
		jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		txtsource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
				"Usa\t", "Srilanka", "Uk", "India", "Canada", "Chinna" }));

		txtdepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
				"Canada\t", "Srilanka", "Uk", "Usa", "India", "Chinna" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(34, 34, 34)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING,
								false)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelFlightID)
												.addComponent(jLabelFlightName))
										.addGroup(jPanel1Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout
														.createSequentialGroup()
														.addGap(38, 38, 38)
														.addComponent(
																txtflightid))
												.addGroup(jPanel1Layout
														.createSequentialGroup()
														.addGap(28, 28, 28)
														.addComponent(
																txtflightname,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																136,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(
										javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addGroup(jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabelSource)
														.addComponent(jLabelDeparture))
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(txtsource,
																0, 136,
																Short.MAX_VALUE)
														.addComponent(txtdepart,
																0,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))))
						.addGap(103, 103, 103)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelDate)
												.addComponent(jLabelDepTime)
												.addComponent(jLabelArrTime))
										.addGap(62, 62, 62)
										.addGroup(jPanel1Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														false)
												.addComponent(txtdate,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														174, Short.MAX_VALUE)
												.addComponent(txtdtime)
												.addComponent(txtarrtime)))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jLabelFlightCharge)
										.addGap(52, 52, 52)
										.addComponent(txtflightcharge,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												172,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(95, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jButtonAdd,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										117,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(29, 29, 29)
								.addComponent(jButtonCancel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										110,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(39, 39, 39)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(36, 36, 36)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabelFlightID)
										.addComponent(txtflightid)
										.addComponent(jLabelDate))
								.addComponent(txtdate,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelFlightName)
								.addComponent(txtflightname,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelDepTime).addComponent(txtdtime,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(28, 28, 28)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelSource)
								.addComponent(txtarrtime,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelArrTime).addComponent(txtsource,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(24, 24, 24)
										.addGroup(jPanel1Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabelDeparture)
												.addComponent(txtdepart,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(34, 34, 34)
										.addGroup(jPanel1Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabelFlightCharge)
												.addComponent(txtflightcharge,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(
								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								93, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonAdd,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										46,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonCancel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										46,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(43, 43, 43)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(34, 34, 34)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(22, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(39, 39, 39)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void autoID() {
		try {
			Class.forName("com.mysql.jdbc.Driver");
			con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline",
					"root", "1234");
			Statement s = con.createStatement();
			ResultSet rs = s.executeQuery("select MAX(id) from flight");
			rs.next();
			rs.getString("MAX(id)");
			if (rs.getString("MAX(id)") == null) {
				txtflightid.setText("FO001");
			} else {
				long id = Long.parseLong(rs.getString("MAX(id)").substring(2,
						rs.getString("MAX(id)").length()));
				id++;
				txtflightid.setText("FO" + String.format("%03d", id));

			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE,
					null, ex);
		} catch (SQLException ex) {
			Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE,
					null, ex);
		}

	}

	public void setID(String id){ this.txtflightid.setText(id);}

	public void setFlightName(String flightName){this.txtflightname.setText(flightName);}

	public void setSource(String source){this.txtsource.setSelectedItem(source);}

	public void setDate(String date) throws ParseException {txtdate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(date));}

	public void setDepartTime(String departTime){this.txtdtime.setText(departTime);}

	public void setArrTime(String arrTime){this.txtarrtime.setText(arrTime);}

	public void setFlightCharge(String charge){this.txtflightcharge.setText(charge);}

	public void setDepart(String depart) {this.txtdepart.setSelectedItem(depart);}

	//public void

	public boolean jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {

		if(!txtflightid.getText().isBlank() && !txtflightname.getText().isBlank() && txtsource.getSelectedItem() != null && txtdepart.getSelectedItem() != null &&
				!txtdtime.getText().isBlank() && !txtarrtime.getText().isBlank() &&
				!txtflightcharge.getText().isBlank()) {
			String id = txtflightid.getText();
			String flightname = txtflightname.getText();

			String source = txtsource.getSelectedItem().toString().trim();
			String depart = txtdepart.getSelectedItem().toString().trim();

			DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
			String date = da.format(txtdate.getDate());

			String departtime = txtdtime.getText();
			String arrtime = txtarrtime.getText();
			String flightcharge = txtflightcharge.getText();

			// Database code here:
			try {
				Class.forName("com.mysql.jdbc.Driver");
				con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline",
						"root", "1234");
				pst = con.prepareStatement(
						"insert into flight(id,flightname,source,depart,date,deptime,arrtime,flightcharge)values(?,?,?,?,?,?,?,?)");

				pst.setString(1, id);
				pst.setString(2, flightname);
				pst.setString(3, source);
				pst.setString(4, depart);
				pst.setString(5, date);
				pst.setString(6, departtime);
				pst.setString(7, arrtime);
				pst.setString(8, flightcharge);

				pst.executeUpdate();
				JOptionPane.showMessageDialog(null, "Flight created...");
			} catch (ClassNotFoundException | SQLException ex) {
				Logger.getLogger(Addflight.class.getName()).log(Level.SEVERE, null,
						ex);
				return false;
			}
		}
		else {
			JOptionPane.showMessageDialog(null, "Field Left Empty...");
			return false;
		}
		return true;

	}

	private void jButtonCancelActionPerformed(ActionEvent evt) {
		this.hide();
	}

}
