package main;
import java.awt.event.ActionListener;

import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Main extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JDesktopPane jDesktopPane1;
	private JMenu jMenuCustomer;
	private JMenu jMenuTickets;
	private JMenu jMenuFlight;
	private JMenu jMenuUser;
	private JMenuBar jMenuBar1;
	private JMenuItem jMenuItemAddCustomer;
	private JMenuItem jMenuItemSearchCustomer;
	private JMenuItem jMenuItemBookTicket;
	private JMenuItem jMenuItemAddFlight;
	private JMenuItem jMenuItemUserCreation;
	private JMenuItem jMenuItemTicketReport;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form Main
	 */
	public Main() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jDesktopPane1 = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenuCustomer = new javax.swing.JMenu();
		jMenuItemAddCustomer = new javax.swing.JMenuItem();
		jMenuItemSearchCustomer = new javax.swing.JMenuItem();
		jMenuTickets = new javax.swing.JMenu();
		jMenuItemBookTicket = new javax.swing.JMenuItem();
		jMenuItemTicketReport = new javax.swing.JMenuItem();
		jMenuFlight = new javax.swing.JMenu();
		jMenuItemAddFlight = new javax.swing.JMenuItem();
		jMenuUser = new javax.swing.JMenu();
		jMenuItemUserCreation = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(1366, 768));

		javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(
				jDesktopPane1);
		jDesktopPane1.setLayout(jDesktopPane1Layout);
		jDesktopPane1Layout.setHorizontalGroup(jDesktopPane1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 400, Short.MAX_VALUE));
		jDesktopPane1Layout.setVerticalGroup(jDesktopPane1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 279, Short.MAX_VALUE));

		jMenuCustomer.setText("Customer");

		jMenuItemAddCustomer.setText("Add Customer");
		jMenuItemAddCustomer.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemAddCusActionPerformed(evt);
			}
		});
		jMenuCustomer.add(jMenuItemAddCustomer);

		jMenuItemSearchCustomer.setText("Search Customer");
		jMenuItemSearchCustomer.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemSearchCusActionPerformed(evt);
			}
		});
		jMenuCustomer.add(jMenuItemSearchCustomer);

		jMenuBar1.add(jMenuCustomer);

		jMenuTickets.setText("Tickets");

		jMenuItemBookTicket.setText("Book Ticket");
		jMenuItemBookTicket
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(
							java.awt.event.ActionEvent evt) {
						jMenuItemBookTicketActionPerformed(evt);
					}
				});
		jMenuTickets.add(jMenuItemBookTicket);

		jMenuItemTicketReport.setText("Ticket Report");
		jMenuItemTicketReport
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(
							java.awt.event.ActionEvent evt) {
						jMenuItemTicketReportActionPerformed(evt);
					}
				});
		jMenuTickets.add(jMenuItemTicketReport);

		jMenuBar1.add(jMenuTickets);

		jMenuFlight.setText("Flight");

		jMenuItemAddFlight.setText("Add Flight");
		jMenuItemAddFlight
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(
							java.awt.event.ActionEvent evt) {
						jMenuItemAddflightActionPerformed(evt);
					}
				});
		jMenuFlight.add(jMenuItemAddFlight);

		jMenuBar1.add(jMenuFlight);

		jMenuUser.setText("User");

		jMenuItemUserCreation.setText("UserCreation");
		jMenuItemUserCreation
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(
							java.awt.event.ActionEvent evt) {
						jMenuItemUserCreationActionPerformed(evt);
					}
				});
		jMenuUser.add(jMenuItemUserCreation);

		jMenuBar1.add(jMenuUser);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jDesktopPane1));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jDesktopPane1));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuItemAddCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		AddCustomer cus = new AddCustomer();
		jDesktopPane1.add(cus);
		cus.setVisible(true);

	}//GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItemSearchCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

		SearchCustomer scus = new SearchCustomer();
		jDesktopPane1.add(scus);
		scus.setVisible(true);

	}//GEN-LAST:event_jMenuItem2ActionPerformed

	private void jMenuItemAddflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
		Addflight f = new Addflight();
		jDesktopPane1.add(f);
		f.setVisible(true);

	}//GEN-LAST:event_jMenuItem4ActionPerformed

	private void jMenuItemBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
		Ticket t = new Ticket();
		jDesktopPane1.add(t);
		t.setVisible(true);

	}//GEN-LAST:event_jMenuItem3ActionPerformed

	private void jMenuItemTicketReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

		Ticketreport ti = new Ticketreport();
		jDesktopPane1.add(ti);
		ti.setVisible(true);

	}//GEN-LAST:event_jMenuItem6ActionPerformed

	private void jMenuItemUserCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

		UserCreation u = new UserCreation();
		jDesktopPane1.add(u);
		u.setVisible(true);

	}//GEN-LAST:event_jMenuItem5ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}
}
